apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - liveness
    readinessProbe:
      httpGet:
        port: 8080
        path: /healthz
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        port: 8080
        path: /healthz
      initialDelaySeconds: 5
      periodSeconds: 10